"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NEW_PAGE = exports.DELETE_COMPONENT = exports.DUPLICATE_COMPONENT = exports.NEW_COMPONENT = exports.ADD_NEW_STATE = exports.CREATE_ACTION = exports.RE_NAME_COMPONENT = exports.GEN_PROP_TYPES_REQUEST = exports.GEN_COMPONENT_REQUEST = exports.LOAD_COMPONENT_REQUEST = exports.CHECK_FILE_EXIST = exports.GET_FOLDER_FILES = exports.CREATE_I18N = exports.CREATE_NEW_ACTION = exports.CHANGE_FUNCTION = exports.CHANGE_LANGUAGE = void 0;
exports.CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
exports.CHANGE_FUNCTION = 'CHANGE_FUNCTION';
exports.CREATE_NEW_ACTION = 'CREATE_NEW_ACTION';
exports.CREATE_I18N = 'CREATE_I18N';
exports.GET_FOLDER_FILES = 'GET_FOLDER_FILES';
exports.CHECK_FILE_EXIST = 'CHECK_FILE_EXIST';
exports.LOAD_COMPONENT_REQUEST = 'LOAD_COMPONENT_REQUEST';
exports.GEN_COMPONENT_REQUEST = 'GEN_COMPONENT_REQUEST';
exports.GEN_PROP_TYPES_REQUEST = 'GEN_PROP_TYPES_REQUEST';
exports.RE_NAME_COMPONENT = 'Rename Component';
exports.CREATE_ACTION = 'Create Action';
exports.ADD_NEW_STATE = 'Add New State';
exports.NEW_COMPONENT = 'New Component';
exports.DUPLICATE_COMPONENT = 'Duplicate Component';
exports.DELETE_COMPONENT = 'Delete Component';
exports.NEW_PAGE = 'New Page';
//# sourceMappingURL=constant.message.js.map